name: 'Dependency Review'
on: [pull_request]

jobs:
  dependency-review:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # ratchet:actions/checkout@v3.5.1
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@c090f4e553673e6e505ea70d6a95362ee12adb94 # ratchet:actions/dependency-review-action@v3.0.3
