name: 'Dependency Review'
on: [pull_request]

jobs:
  dependency-review:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # ratchet:actions/checkout@v3.5.2
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@c090f4e553673e6e505ea70d6a95362ee12adb94 # ratchet:actions/dependency-review-action@v3.0.3
