name: Nightly Build
on:
  schedule:
    # Random minute number to avoid GH scheduler stampede
    - cron: '37 21 * * *'
  workflow_dispatch: {}

env:
  NIGHTLY: true

jobs:
  build-and-publish-images:
    runs-on: ubuntu-20.04

    permissions:
      contents: read
      id-token: write
      packages: write

    env:
      COSIGN_EXPERIMENTAL: 1

    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # ratchet:actions/checkout@v3.3.0
      - name: Install cosign
        uses: sigstore/cosign-installer@9e9de2292db7abb3f51b7f4808d98f0d347a8919 # ratchet:sigstore/cosign-installer@v3.0.2
        with:
          cosign-release: v1.13.1
      - name: Install regctl
        uses: regclient/actions/regctl-installer@b6614f5f56245066b533343a85f4109bdc38c8cc # ratchet:regclient/actions/regctl-installer@main
      - name: Build images
        run: make images load-images
      - name: Log in to GHCR
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # ratchet:docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push images
        run: ./.github/workflows/scripts/push-images.sh nightly
